rails3.0/lunch42/config/routes.rb
Lunch42::Application.routes.draw do

  resources :categories

  resources :venues

  root :to => "venues#index"

end

rails3.0/lunch42/app/models/category.rb
class Category < ActiveRecord::Base
end

rails3.0/lunch42/app/models/venue.rb
class Venue < ActiveRecord::Base
end

rails3.0/lunch42/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

rails3.0/lunch42/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.xml
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.xml
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.xml
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.xml
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to(@category, :notice => 'Category was successfully created.') }
        format.xml  { render :xml => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.xml
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to(@category, :notice => 'Category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.xml
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to(categories_url) }
      format.xml  { head :ok }
    end
  end
end

rails3.0/lunch42/app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  # GET /venues
  # GET /venues.xml
  def index
    @venues = Venue.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @venues }
    end
  end

  # GET /venues/1
  # GET /venues/1.xml
  def show
    @venue = Venue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @venue }
    end
  end

  # GET /venues/new
  # GET /venues/new.xml
  def new
    @venue = Venue.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @venue }
    end
  end

  # GET /venues/1/edit
  def edit
    @venue = Venue.find(params[:id])
  end

  # POST /venues
  # POST /venues.xml
  def create
    @venue = Venue.new(params[:venue])

    respond_to do |format|
      if @venue.save
        format.html { redirect_to(@venue, :notice => 'Venue was successfully created.') }
        format.xml  { render :xml => @venue, :status => :created, :location => @venue }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @venue.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /venues/1
  # PUT /venues/1.xml
  def update
    @venue = Venue.find(params[:id])

    respond_to do |format|
      if @venue.update_attributes(params[:venue])
        format.html { redirect_to(@venue, :notice => 'Venue was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @venue.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1
  # DELETE /venues/1.xml
  def destroy
    @venue = Venue.find(params[:id])
    @venue.destroy

    respond_to do |format|
      format.html { redirect_to(venues_url) }
      format.xml  { head :ok }
    end
  end
end

rails3.0/lunch42/app/helpers/application_helper.rb
module ApplicationHelper
end

rails3.0/lunch42/app/helpers/categories_helper.rb
module CategoriesHelper
end

rails3.0/lunch42/app/helpers/venues_helper.rb
module VenuesHelper
end

rails3.0/lunch42/app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails3.0/lunch42/app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

rails3.0/lunch42/app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Rating</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= category.description %></td>
    <td><%= category.rating %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

rails3.0/lunch42/app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

rails3.0/lunch42/app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<p>
  <b>Description:</b>
  <%= @category.description %>
</p>

<p>
  <b>Rating:</b>
  <%= @category.rating %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

rails3.0/lunch42/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lunch42</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

rails3.0/lunch42/app/views/venues/_form.html.erb
<%= form_for(@venue) do |f| %>
  <% if @venue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@venue.errors.count, "error") %> prohibited this venue from being saved:</h2>

      <ul>
      <% @venue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :address1 %><br />
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br />
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br />
    <%= f.text_field :zipcode %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :distance %><br />
    <%= f.text_field :distance %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails3.0/lunch42/app/views/venues/edit.html.erb
<h1>Editing venue</h1>

<%= render 'form' %>

<%= link_to 'Show', @venue %> |
<%= link_to 'Back', venues_path %>

rails3.0/lunch42/app/views/venues/index.html.erb
<h1>Listing venues</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Address1</th>
    <th>Address2</th>
    <th>City</th>
    <th>State</th>
    <th>Zipcode</th>
    <th>Phone</th>
    <th>Distance</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @venues.each do |venue| %>
  <tr>
    <td><%= venue.name %></td>
    <td><%= venue.description %></td>
    <td><%= venue.address1 %></td>
    <td><%= venue.address2 %></td>
    <td><%= venue.city %></td>
    <td><%= venue.state %></td>
    <td><%= venue.zipcode %></td>
    <td><%= venue.phone %></td>
    <td><%= venue.distance %></td>
    <td><%= link_to 'Show', venue %></td>
    <td><%= link_to 'Edit', edit_venue_path(venue) %></td>
    <td><%= link_to 'Destroy', venue, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Venue', new_venue_path %>

rails3.0/lunch42/app/views/venues/new.html.erb
<h1>New venue</h1>

<%= render 'form' %>

<%= link_to 'Back', venues_path %>

rails3.0/lunch42/app/views/venues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @venue.name %>
</p>

<p>
  <b>Description:</b>
  <%= @venue.description %>
</p>

<p>
  <b>Address1:</b>
  <%= @venue.address1 %>
</p>

<p>
  <b>Address2:</b>
  <%= @venue.address2 %>
</p>

<p>
  <b>City:</b>
  <%= @venue.city %>
</p>

<p>
  <b>State:</b>
  <%= @venue.state %>
</p>

<p>
  <b>Zipcode:</b>
  <%= @venue.zipcode %>
</p>

<p>
  <b>Phone:</b>
  <%= @venue.phone %>
</p>

<p>
  <b>Distance:</b>
  <%= @venue.distance %>
</p>


<%= link_to 'Edit', edit_venue_path(@venue) %> |
<%= link_to 'Back', venues_path %>